/*
 * App URI: anotherModel
 * Source Location: anotherModel.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5980), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("anotherModel", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * llmUpgrade.js - Qwen3-0.6B 최신화 버전
			 ************************************************/
			var globalAIEngine = null;

			function onBodyLoad(e){
			    // 워커 생성
			    const worker = new Worker(new URL("./lib/llm-worker.js", window.location.href), { type: "module" });

			    import("./lib/web-llm.js").then(async function(webllm) {
			        console.log("⏳ 최신 0.6B급 엔진(Qwen) 로딩 시작...");

			        const modelId = "Qwen3-0.6B-MLC"; 
			        
			        // 💡 새 폴더 경로 매핑
			        const absoluteModelUrl = new URL("./lib/Qwen3-0.6B-q0f16-MLC/", window.location.href).href;
			        const absoluteWasmUrl = new URL("./lib/Qwen3-0.6B-q0f16-MLC/Qwen3-0.6B-q0f16-ctx4k_cs1k-webgpu.wasm", window.location.href).href;

			        const customAppConfig = {
			            model_list: [
			                {
			                    model_id: modelId,
			                    model: absoluteModelUrl, 
			                    model_lib: absoluteWasmUrl
			                }
			            ]
			        };

			        globalAIEngine = await webllm.CreateWebWorkerMLCEngine(worker, modelId, {
			            appConfig: customAppConfig,
			            initProgressCallback: (progress) => {
			                console.log(`[AI 로딩] ${Math.round(progress.progress * 100)}% : ${progress.text}`);
			            }
			        });

			        console.log("🚀 0.6B 엔진 준비 완료! 광속 분석이 시작됩니다.");
			    });
			}

			/**
			 * 버튼 클릭 이벤트 (스트리밍 로직 포함)
			 */
			async function onBtnSmartGridFillClick(e) {
			    var rawText = app.lookup("txaUserInput").value; 
			    if (!rawText || !globalAIEngine) return alert("입력값이 없거나 AI가 준비되지 않았습니다.");

			    var grid = app.lookup("grd1");
			    var dataSet = grid.dataSet;
			    var todayStr = new Date().toISOString().split('T')[0];
			    
			    // 그리드 헤더 추출 및 포맷 생성
			    var headers = dataSet.getHeaders();
			    var expectedJsonFormat = {};
			    headers.forEach(h => expectedJsonFormat[h.getName()] = "");
			    var formatStr = JSON.stringify(expectedJsonFormat);

			    // 범용 프롬프트 (수량 복제 강조)
			    var systemPrompt = `당신은 데이터 파서입니다. 인사말 없이 [ ] 로 된 JSON 배열만 출력하세요.
[원칙]
1. 수량(건, 명, 개 등)이 파악되면 그 숫자만큼 객체를 물리적으로 복제하여 배열에 넣으세요.
2. 모든 데이터의 구조는 반드시 다음을 따르세요: ${formatStr}
3. 오늘 날짜: ${todayStr}`;

			    try {
			        const chunks = await globalAIEngine.chat.completions.create({
			            messages: [{ role: "system", content: systemPrompt }, { role: "user", content: rawText }],
			            temperature: 0.1,
			            stream: true 
			        });

			        let fullReply = "";
			        for await (const chunk of chunks) {
			            fullReply += (chunk.choices[0]?.delta?.content || "");
			            if(app.lookup("optLog")) app.lookup("optLog").value = fullReply; 
			        }

			        // JSON 추출 및 그리드 반영
			        var jsonMatch = fullReply.match(/\[[\s\S]*\]/);
			        var extractedArray = JSON.parse(jsonMatch ? jsonMatch[0] : "[" + fullReply.match(/\{[\s\S]*\}/)[0] + "]");

			        extractedArray.forEach(rowData => {
			            // 여기에 코드 딕셔너리 변환 로직 추가 가능
			            dataSet.addRowData(rowData);
			        });
			        
			        app.getContainer().redraw();
			        alert(extractedArray.length + "건 추가 완료!");

			    } catch(err) {
			        console.error("추론 실패:", err);
			    }
			}
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsOrder");
			dataSet_1.parseData({
				"columns" : [
					{"name": "reqDate"},
					{"name": "clientName"},
					{"name": "itemName"},
					{"name": "orderCount"},
					{"name": "food"}
				]
			});
			app.register(dataSet_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "Button";
			if(typeof onBtnSmartGridFillClick == "function") {
				button_1.addEventListener("click", onBtnSmartGridFillClick);
			}
			container.addChild(button_1, {
				"top": "38px",
				"left": "685px",
				"width": "144px",
				"height": "40px"
			});
			
			var textArea_1 = new cpr.controls.TextArea("txaUserInput");
			textArea_1.value = "영업팀입니다. 다음 주 수요일까지 카카오엔터프라이즈 측에 최신형 서버 랙 15대 발주 처리 부탁드립니다. 빠른 처리 요망.";
			container.addChild(textArea_1, {
				"top": "10px",
				"left": "10px",
				"width": "553px",
				"height": "137px"
			});
			
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"dataSet": app.lookup("dsOrder"),
				"columns": [
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "reqDate";
								cell.text = "reqDate";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "clientName";
								cell.text = "clientName";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "itemName";
								cell.text = "itemName";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "orderCount";
								cell.text = "orderCount";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "food";
								cell.text = "food";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnName = "reqDate";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "clientName";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "itemName";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.columnName = "orderCount";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.columnName = "food";
							}
						}
					]
				}
			});
			container.addChild(grid_1, {
				"top": "194px",
				"left": "20px",
				"width": "860px",
				"height": "328px"
			});
			
			var output_1 = new cpr.controls.Output("optLog");
			output_1.value = "Output";
			output_1.unselectable = false;
			container.addChild(output_1, {
				"top": "543px",
				"left": "13px",
				"width": "873px",
				"height": "1695px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "anotherModel";
	cpr.core.Platform.INSTANCE.register(app);
})();
