/*
 * App URI: QwenFilter
 * Source Location: QwenFilter.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5980), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("QwenFilter", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// llm_smart_search.js - eXBuilder6 자연어 검색/필터/정렬 시스템

			var globalAIEngine = null;

			function onBodyLoad(e){
			    // 기존 AI 엔진 초기화 코드 (동일)
			    const worker = new Worker(new URL("./lib/llm-worker.js", window.location.href), { type: "module" });

			    worker.onerror = function(err) {
			        console.error("🚨 [Worker 에러]:", err.message);
			    };

			    import("./lib/web-llm.js").then(async function(webllm) {
			        console.log("⏳ 폐쇄망 로컬 AI 엔진 예열 시작...");

			        const modelId = "Qwen2.5-0.5B-Local"; 
			        
			        const absoluteModelUrl = new URL("./lib/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/", window.location.href).href;
			        const absoluteWasmUrl = new URL("./lib/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/Qwen2-0.5B-Instruct-q4f16_1-ctx4k_cs1k-webgpu.wasm", window.location.href).href;

			        const customAppConfig = {
			            model_list: [
			                {
			                    model_id: modelId,
			                    model: absoluteModelUrl, 
			                    model_lib: absoluteWasmUrl 
			                }
			            ]
			        };

			        var logCtrl = app.lookup("optLog");
			        
			        globalAIEngine = await webllm.CreateWebWorkerMLCEngine(worker, modelId, {
			            appConfig: customAppConfig,
			            initProgressCallback: (progress) => {
			                var progressText = `[AI 로컬 로딩] ${Math.round(progress.progress * 100)}% : ${progress.text}`;
			                console.log(progressText);
			                
			                if (logCtrl) {
			                    logCtrl.value = progressText;
			                    app.getContainer().redraw();
			                }
			            }
			        });

			        console.log("✅ AI 폐쇄망 예열 완료!");
			        if (logCtrl) {
			            logCtrl.value = "✅ AI 엔진 세팅 완료! 자연어 검색 준비 끝.";
			            app.getContainer().redraw();
			        }

			    }).catch(function(error) {
			        console.error("❌ AI 초기화 실패:", error);
			    });
			}

			/*
			 * 🔍 "스마트 검색" 버튼 클릭 이벤트
			 * 자연어 입력 → AI 분석 → 정렬/필터 자동 적용
			 */
			async function onBtnSmartSearchClick(e) {
			    var rawText = app.lookup("txaUserInput").value; 
			    if (!rawText) return alert("검색할 내용을 입력해주세요.");

			    if (!globalAIEngine) {
			        return alert("AI가 아직 예열 중입니다. 상단 로그를 확인해주세요.");
			    }

			    var dataSet = app.lookup("dsOrder"); // 데이터셋 ID는 실제 환경에 맞게 수정
			    var headers = dataSet.getHeaders(); 
			    
			    // 전체 컬럼 목록 추출
			    var allowedColumns = [];
			    for(var i = 0; i < headers.length; i++) {
			        allowedColumns.push(headers[i].getName());
			    }

			    // ⭐ AI 프롬프트: 자연어 → 구조화된 검색 명령 변환
			    var systemPrompt = `당신은 사용자의 자연어 검색 요청을 분석하여 데이터베이스 명령으로 변환하는 전문가입니다.
사용자의 요청을 정확히 분석하여 아래 형식으로만 출력하세요.

[🎯 절대 규칙]
1. 불필요한 인사말이나 설명 없이 오직 결과만 출력
2. 아래 형식 중 하나만 선택하여 정확히 출력
3. 컬럼명은 반드시 사용 가능한 컬럼 목록에서만 선택
4. 사용자가 입력한 원본 값은 절대 수정하지 말고 그대로 사용

[📋 사용 가능한 컬럼 목록]
${allowedColumns.join(", ")}

[🔧 출력 형식]

✅ 정렬 요청인 경우:
SORT|컬럼명|정렬방향
- 정렬방향: asc (오름차순/작은것부터/적은순) 또는 desc (내림차순/큰것부터/많은순)

예시:
- "나이 많은 순으로" → SORT|age|desc
- "age 컬럼 큰것부터" → SORT|age|desc
- "가격 낮은 순" → SORT|price|asc
- "이름 순서대로" → SORT|name|asc

✅ 필터 요청인 경우:
FILTER|컬럼명|연산자|값
- 연산자: == (같음), != (다름), *= (포함), > (크다), < (작다), >= (이상), <= (이하)

예시:
- "사과만 보여줘" → FILTER|food|==|사과
- "food에서 사과" → FILTER|food|==|사과
- "나이 20 이상" → FILTER|age|>=|20
- "이름에 김 포함" → FILTER|name|*=|김

✅ 정렬 + 필터 동시 요청인 경우:
MULTI|FILTER|컬럼명|연산자|값|SORT|컬럼명|정렬방향

예시:
- "사과만 가격순으로" → MULTI|FILTER|food|==|사과|SORT|price|asc

[🚨 주의사항]
1. 컬럼명이 명확하지 않으면 가장 유사한 컬럼 선택
2. 값은 사용자가 입력한 그대로 사용 (맞춤법 수정 금지)
3. 숫자는 숫자로, 문자는 문자로 정확히 구분
4. 불가능한 요청은 ERROR|이유 형식으로 출력

이제 아래 사용자 요청을 분석하여 정확한 명령으로 변환하세요:`;

			    try {
			        console.log("🚀 백그라운드 AI 검색 명령 분석 시작...");
			        var logCtrl = app.lookup("optLog");
			        
			        const chunks = await globalAIEngine.chat.completions.create({
			            messages: [
			                { role: "system", content: systemPrompt },
			                { role: "user", content: rawText }
			            ],
			            temperature: 0.0, 
			            max_tokens: 50,
			            stream: true 
			        });

			        let fullReply = "";
			        
			        for await (const chunk of chunks) {
			            const content = chunk.choices[0]?.delta?.content || "";
			            fullReply += content;
			            if(logCtrl) {
			                logCtrl.value = "AI 분석 중... " + fullReply; 
			                app.getContainer().redraw();
			            }
			        }

			        console.log("✅ AI 분석 완료:", fullReply);

			        // 3. AI 응답 파싱 및 실행
			        var cleanReply = fullReply.trim().replace(/`/g, "");
			        
			        if (cleanReply.startsWith("ERROR")) {
			            var errorMsg = cleanReply.split("|")[1] || "요청을 이해할 수 없습니다";
			            return alert("❌ " + errorMsg);
			        }

			        // 명령 실행
			        executeSearchCommand(dataSet, cleanReply, logCtrl);

			    } catch(error) {
			        console.error("❌ 처리 오류:", error);
			        alert("분석 중 오류가 발생했습니다. 콘솔을 확인하세요.");
			    }
			}

			/*
			 * 🎯 검색 명령 실행 함수
			 */
			function executeSearchCommand(dataSet, command, logCtrl) {
			    var parts = command.split("|");
			    var cmdType = parts[0];

			    try {
			        if (cmdType === "SORT") {
			            // SORT|컬럼명|정렬방향
			            var column = parts[1];
			            var order = parts[2]; // asc 또는 desc
			            
			            var sortExpr = column + " " + order;
			            
			            dataSet.setSort(sortExpr);
			            
			            console.log("✅ 정렬 적용:", sortExpr);
			            if(logCtrl) {
			                logCtrl.value = "✅ 정렬 완료: " + column + " " + (order === "desc" ? "내림차순" : "오름차순");
			            }
			            alert("정렬 완료: " + column + " " + (order === "desc" ? "큰 것부터" : "작은 것부터"));
			            
			        } else if (cmdType === "FILTER") {
			            // FILTER|컬럼명|연산자|값
			            var column = parts[1];
			            var operator = parts[2];
			            var value = parts[3];
			            
			            var filterExpr = column + " " + operator + " '" + value + "'";
			            dataSet.setFilter(filterExpr);
			            
			            console.log("✅ 필터 적용:", filterExpr);
			            if(logCtrl) {
			                logCtrl.value = "✅ 필터 완료: " + column + " " + operator + " " + value;
			            }
			            alert("필터 완료: " + column + "에서 " + value + " 조건 적용");
			            
			        } else if (cmdType === "MULTI") {
			            // MULTI|FILTER|컬럼명|연산자|값|SORT|컬럼명|정렬방향
			            var hasSort = false;
			            var hasFilter = false;
			            var sortColumn, sortOrder, filterColumn, filterOperator, filterValue;
			            
			            // SORT 찾기
			            for(var i = 1; i < parts.length; i++) {
			                if(parts[i] === "SORT" && i + 2 < parts.length) {
			                    sortColumn = parts[i + 1];
			                    sortOrder = parts[i + 2];
			                    hasSort = true;
			                }
			            }
			            
			            // FILTER 찾기
			            for(var i = 1; i < parts.length; i++) {
			                if(parts[i] === "FILTER" && i + 3 < parts.length) {
			                    filterColumn = parts[i + 1];
			                    filterOperator = parts[i + 2];
			                    filterValue = parts[i + 3];
			                    hasFilter = true;
			                }
			            }
			            
			            // 필터 먼저 적용
			            if(hasFilter) {
			                var filterExpr = filterColumn + " " + filterOperator + " '" + filterValue + "'";
			                dataSet.setFilter(filterExpr);
			                console.log("✅ 필터 적용:", filterExpr);
			            }
			            
			            // 정렬 적용
			            if(hasSort) {
			                var sortExpr = sortColumn + " " + sortOrder;
			                dataSet.setSort(sortExpr);
			                console.log("✅ 정렬 적용:", sortExpr);
			            }
			            
			            if(logCtrl) {
			                var msg = "✅ ";
			                if(hasFilter) msg += "필터(" + filterColumn + ") + ";
			                if(hasSort) msg += "정렬(" + sortColumn + " " + sortOrder + ")";
			                logCtrl.value = msg;
			            }
			            alert("필터 및 정렬 완료!");
			            
			        } else {
			            alert("❌ 알 수 없는 명령 형식입니다: " + command);
			        }
			        
			        // 화면 갱신
			        app.getContainer().redraw();
			        
			    } catch(error) {
			        console.error("❌ 명령 실행 오류:", error);
			        alert("명령 실행 중 오류 발생: " + error.message);
			    }
			}

			/*
			 * 🔄 "필터 초기화" 버튼 클릭 이벤트
			 */
			function onBtnResetFilterClick(e) {
			    var dataSet = app.lookup("dsOrder");
			    
			    // 필터 및 정렬 초기화
			    dataSet.setFilter("");
			    dataSet.setSort("");
			    
			    var logCtrl = app.lookup("optLog");
			    if(logCtrl) {
			        logCtrl.value = "🔄 필터 및 정렬 초기화 완료";
			    }
			    
			    app.getContainer().redraw();
			    alert("필터 및 정렬이 초기화되었습니다.");
			}

			/*
			 * 📊 "현재 상태 보기" 버튼 클릭 이벤트
			 */
			function onBtnShowStatusClick(e) {
			    var dataSet = app.lookup("dsOrder");
			    
			    var currentFilter = dataSet.getFilter() || "(없음)";
			    var currentSort = dataSet.getSort() || "(없음)";
			    var rowCount = dataSet.getRowCount();
			    
			    var statusMsg = "📊 현재 데이터셋 상태\n\n";
			    statusMsg += "🔍 필터: " + currentFilter + "\n";
			    statusMsg += "📈 정렬: " + currentSort + "\n";
			    statusMsg += "📝 표시된 행 수: " + rowCount + "개";
			    
			    alert(statusMsg);
			    
			    var logCtrl = app.lookup("optLog");
			    if(logCtrl) {
			        logCtrl.value = "필터: " + currentFilter + " | 정렬: " + currentSort;
			    }
			}
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsOrder");
			dataSet_1.parseData({
				"columns" : [
					{"name": "reqDate"},
					{"name": "clientName"},
					{"name": "itemName"},
					{"name": "orderCount"},
					{"name": "food"}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("ds1");
			dataSet_2.parseData({
				"columns": [
					{
						"name": "column1",
						"dataType": "number"
					},
					{"name": "column2"},
					{"name": "column3"}
				],
				"rows": [
					{"column1": "1", "column2": "column21", "column3": "짜장면"},
					{"column1": "2", "column2": "column22", "column3": "column32"},
					{"column1": "3", "column2": "column23", "column3": "column33"},
					{"column1": "4", "column2": "column24", "column3": "column34"},
					{"column1": "5", "column2": "column25", "column3": "column35"},
					{"column1": "6", "column2": "column26", "column3": "column36"},
					{"column1": "7", "column2": "column27", "column3": "column37"}
				]
			});
			app.register(dataSet_2);
			var dataMap_1 = new cpr.data.DataMap("dmSample");
			dataMap_1.parseData({
				"columns" : [
					{
						"name": "reqDate",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "clientName",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "itemName",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "orderCount",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "food",
						"dataType": "string",
						"displayOnly": false
					}
				]
			});
			app.register(dataMap_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "Button";
			if(typeof onBtnSmartSearchClick == "function") {
				button_1.addEventListener("click", onBtnSmartSearchClick);
			}
			container.addChild(button_1, {
				"top": "38px",
				"left": "685px",
				"width": "144px",
				"height": "40px"
			});
			
			var textArea_1 = new cpr.controls.TextArea("txaUserInput");
			textArea_1.value = "오늘 날짜로 임채명 데이터추가";
			container.addChild(textArea_1, {
				"top": "10px",
				"left": "10px",
				"width": "553px",
				"height": "137px"
			});
			
			var output_1 = new cpr.controls.Output("optLog");
			output_1.value = "Output";
			output_1.unselectable = false;
			container.addChild(output_1, {
				"top": "523px",
				"left": "13px",
				"width": "873px",
				"height": "1314px"
			});
			
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"dataSet": app.lookup("ds1"),
				"columns": [
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "column1";
								cell.text = "column1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "column2";
								cell.text = "column2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "column3";
								cell.text = "column3";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnName = "column1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "column2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "column3";
							}
						}
					]
				}
			});
			container.addChild(grid_1, {
				"top": "206px",
				"left": "46px",
				"width": "796px",
				"height": "224px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "QwenFilter";
	cpr.core.Platform.INSTANCE.register(app);
})();
