/*
 * App URI: QwenDm
 * Source Location: QwenDm.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5980), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("QwenDm", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// llmUpgrade.js

			var globalAIEngine = null;

			function onBodyLoad(e){
			    const worker = new Worker(new URL("./lib/llm-worker.js", window.location.href), { type: "module" });

			    worker.onerror = function(err) {
			        console.error("🚨 [Worker 에러]:", err.message);
			    };

			    import("./lib/web-llm.js").then(async function(webllm) {
			        console.log("⏳ 폐쇄망 로컬 AI 엔진 예열 시작...");

			        const modelId = "Qwen2.5-0.5B-Local"; 
			        
			        const absoluteModelUrl = new URL("./lib/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/", window.location.href).href;
			        const absoluteWasmUrl  = new URL("./lib/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/Qwen2-0.5B-Instruct-q4f16_1-ctx4k_cs1k-webgpu.wasm", window.location.href).href;

			        const customAppConfig = {
			            model_list: [{
			                model_id: modelId,
			                model:     absoluteModelUrl,
			                model_lib: absoluteWasmUrl
			            }]
			        };

			        var logCtrl = app.lookup("optLog");
			        
			        globalAIEngine = await webllm.CreateWebWorkerMLCEngine(worker, modelId, {
			            appConfig: customAppConfig,
			            initProgressCallback: (progress) => {
			                var progressText = `[AI 로컬 로딩] ${Math.round(progress.progress * 100)}% : ${progress.text}`;
			                console.log(progressText);
			                if (logCtrl) { logCtrl.value = progressText; app.getContainer().redraw(); }
			            }
			        });

			        console.log("✅ AI 폐쇄망 예열 완료!");
			        if (logCtrl) { logCtrl.value = "✅ AI 엔진 세팅 완료! 오프라인 동작 준비 끝."; app.getContainer().redraw(); }

			    }).catch(function(error) {
			        console.error("❌ AI 초기화 실패:", error);
			    });
			}

			// ─────────────────────────────────────────────────────────────────────────────
			// 유틸 1: 날짜 포맷 헬퍼
			// ─────────────────────────────────────────────────────────────────────────────
			function fmtDate(d) {
			    return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
			}

			// ─────────────────────────────────────────────────────────────────────────────
			// 유틸 2: ⭐ 핵심 수정 - AI에게 넘기기 전에 JS에서 직접 날짜 치환
			//   "오늘날짜로 임채명 추가해" → "2026-03-31 임채명 추가해"
			//   AI는 이미 변환된 실제 값만 보게 됨
			// ─────────────────────────────────────────────────────────────────────────────
			function preprocessDateExpressions(text) {
			    const now = new Date();
			    const today     = fmtDate(now);
			    const yesterday = fmtDate(new Date(now - 86400000));
			    const tomorrow  = fmtDate(new Date(now + 86400000));
			    const thisMonth = today.slice(0, 7);
			    const thisYear  = String(now.getFullYear());

			    return text
			        // 복합 표현 먼저 (긴 것 우선 매칭)
			        .replace(/오늘\s*날짜/g,  today)
			        .replace(/현재\s*날짜/g,  today)
			        .replace(/현재\s*일자/g,  today)
			        .replace(/오늘\s*일자/g,  today)
			        .replace(/이번\s*달/g,    thisMonth)
			        .replace(/이번\s*월/g,    thisMonth)
			        // 단독 표현
			        .replace(/오늘/g,         today)
			        .replace(/현재/g,         today)
			        .replace(/어제/g,         yesterday)
			        .replace(/내일/g,         tomorrow)
			        .replace(/올해/g,         thisYear)
			        .replace(/금년/g,         thisYear);
			}

			// ─────────────────────────────────────────────────────────────────────────────
			// 유틸 3: 금액 문자열 → 숫자 변환  "150만원" → "1500000"
			// ─────────────────────────────────────────────────────────────────────────────
			function parseAmount(val) {
			    val = val.replace(/,/g, "").trim();
			    if (/억/.test(val)) return String(Math.round(parseFloat(val.replace(/[^0-9.]/g, "")) * 100000000));
			    if (/만/.test(val)) return String(Math.round(parseFloat(val.replace(/[^0-9.]/g, "")) * 10000));
			    var stripped = val.replace(/[^0-9.]/g, "");
			    return stripped || val;
			}

			// ─────────────────────────────────────────────────────────────────────────────
			// 유틸 4: Levenshtein 유사도 기반 컬럼 보정
			// ─────────────────────────────────────────────────────────────────────────────
			function calcSimilarity(a, b) {
			    a = a.toLowerCase(); b = b.toLowerCase();
			    if (a === b) return 1;
			    const la = a.length, lb = b.length;
			    const dp = Array.from({length: la+1}, (_, i) =>
			        Array.from({length: lb+1}, (_, j) => i === 0 ? j : j === 0 ? i : 0)
			    );
			    for (let i = 1; i <= la; i++)
			        for (let j = 1; j <= lb; j++)
			            dp[i][j] = a[i-1] === b[j-1] ? dp[i-1][j-1] : 1 + Math.min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]);
			    return 1 - dp[la][lb] / Math.max(la, lb);
			}

			function resolveColumn(predicted, colNames, threshold) {
			    threshold = threshold || 0.5;
			    if (colNames.indexOf(predicted) !== -1) return predicted;
			    const lower = predicted.toLowerCase();
			    const exactCI = colNames.find(function(c) { return c.toLowerCase() === lower; });
			    if (exactCI) return exactCI;
			    var best = null, bestScore = 0;
			    for (var i = 0; i < colNames.length; i++) {
			        var score = calcSimilarity(predicted, colNames[i]);
			        if (score > bestScore) { bestScore = score; best = colNames[i]; }
			    }
			    if (bestScore >= threshold) {
			        console.log('🔧 컬럼 보정: "' + predicted + '" → "' + best + '" (유사도 ' + (bestScore*100).toFixed(0) + '%)');
			        return best;
			    }
			    return null;
			}

			// ─────────────────────────────────────────────────────────────────────────────
			// 유틸 5: camelCase → 의미 힌트 ("deliveryDate" → "delivery date")
			// ─────────────────────────────────────────────────────────────────────────────
			function camelToWords(str) {
			    return str.replace(/([A-Z])/g, ' $1').trim().toLowerCase();
			}

			// ─────────────────────────────────────────────────────────────────────────────
			// 메인: "스마트 데이터맵 채우기" 버튼 클릭
			// ─────────────────────────────────────────────────────────────────────────────
			async function onBtnSmartMapFillClick(e) {
			    var rawText = app.lookup("txaUserInput").value;
			    if (!rawText) return alert("입력할 데이터를 텍스트로 작성해주세요.");
			    if (!globalAIEngine) return alert("AI가 아직 예열 중입니다. 상단 로그를 확인해주세요.");

			    // ⭐ 날짜 표현을 AI 이전에 JS에서 먼저 실제 값으로 치환
			    var processedText = preprocessDateExpressions(rawText);
			    console.log("📝 전처리된 입력:", processedText);

			    var dataMap  = app.lookup("dmSample");
			    var colNames = dataMap.getColumnNames();

			    // 컬럼 힌트 문자열 생성 (camelCase 분리로 AI가 의미 파악)
			    var colHints = colNames.map(function(c) { return c + "(" + camelToWords(c) + ")"; }).join(", ");

			    // ─── 소형 모델(0.5B)용 최소화 프롬프트 ──────────────────────
			    // 규칙이 많을수록 0.5B 모델은 혼란 → 영어로 짧고 명확하게
			    var systemPrompt =
			        "Extract data from the user's Korean text and map to the most semantically similar column.\n\n" +
			        "Available columns: " + colHints + "\n\n" +
			        "Rules:\n" +
			        "- Output ONLY lines in format: columnName|value\n" +
			        "- Use exact column names from the list above\n" +
			        "- Remove Korean particles (은/는/이/가/을/를/로) and filler words (넣어/추가/입력/해줘/해)\n" +
			        "- No explanations, no JSON, no markdown\n\n" +
			        "Example:\n" +
			        "Input: \"2026-03-31 홍길동 데이터 넣어줘\"\n" +
			        "Output:\n" +
			        "regDate|2026-03-31\n" +
			        "userName|홍길동";

			    try {
			        var logCtrl = app.lookup("optLog");
			        if (logCtrl) { logCtrl.value = "🤖 AI 분석 중..."; app.getContainer().redraw(); }

			        console.log("🚀 AI DataMap 스마트 매핑 시작...");

			        const chunks = await globalAIEngine.chat.completions.create({
			            messages: [
			                { role: "system", content: systemPrompt },
			                { role: "user",   content: processedText }  // ⭐ 전처리된 텍스트 전달
			            ],
			            temperature: 0.0,
			            stream: true
			        });

			        var fullReply = "";
			        for await (const chunk of chunks) {
			            var content = chunk.choices[0]?.delta?.content || "";
			            fullReply += content;
			            if (logCtrl) { logCtrl.value = fullReply; app.getContainer().redraw(); }
			        }

			        console.log("✅ AI 응답 완료:\n" + fullReply);

			        // ─── 파싱 ───────────────────────────────────────────────
			        var lines = fullReply
			            .replace(/```[\s\S]*?```/g, "")
			            .replace(/`/g, "")
			            .trim()
			            .split("\n")
			            .map(function(l) { return l.trim(); })
			            .filter(Boolean);

			        if (!lines.length) return alert("매핑할 데이터를 추출하지 못했습니다.\nAI 응답: " + fullReply);

			        // ─── 공통 코드 딕셔너리 ─────────────────────────────────
			        var codeDictionaries = {
			            "deptCode":     { "영업팀": "DEPT_001", "인사팀": "DEPT_002", "IT팀": "DEPT_003" },
			            "bankCode":     { "국민은행": "KB_04", "신한은행": "SH_05", "우리은행": "WR_06" },
			            "itemCategory": { "모니터": "CAT_M", "마우스": "CAT_MO", "키보드": "CAT_K" }
			        };

			        // ─── DataMap 세팅 ────────────────────────────────────────
			        var updateCount = 0;
			        var skipped = [];

			        for (var i = 0; i < lines.length; i++) {
			            var line = lines[i];
			            if (!line.includes("|")) { skipped.push(line); continue; }

			            var pipeIdx      = line.indexOf("|");
			            var predictedCol = line.slice(0, pipeIdx).trim();
			            var targetVal    = line.slice(pipeIdx + 1).trim();
			            if (!predictedCol || !targetVal) continue;

			            var resolvedCol = resolveColumn(predictedCol, colNames, 0.5);
			            if (!resolvedCol) {
			                console.warn("⚠️ 매칭 컬럼 없음, 무시:", predictedCol, "→", targetVal);
			                skipped.push(predictedCol + "|" + targetVal);
			                continue;
			            }

			            // 딕셔너리 변환
			            if (codeDictionaries[resolvedCol] && codeDictionaries[resolvedCol][targetVal]) {
			                targetVal = codeDictionaries[resolvedCol][targetVal];
			            }

			            // 금액 계열 자동 변환
			            if (/amount|price|cost|fee|salary|pay/i.test(resolvedCol)) {
			                targetVal = parseAmount(targetVal);
			            }

			            dataMap.setValue(resolvedCol, targetVal);
			            updateCount++;
			            console.log("✏️ DataMap 세팅: " + resolvedCol + " = " + targetVal);
			        }

			        app.getContainer().redraw();

			        var resultMsg = "✅ " + updateCount + "개 데이터가 반영되었습니다.";
			        if (skipped.length) resultMsg += "\n⚠️ " + skipped.length + "개 무시됨: " + skipped.join(", ");
			        alert(resultMsg);

			        if (logCtrl) {
			            logCtrl.value = "✅ 매핑 완료! " + updateCount + "개 세팅 / " + skipped.length + "개 무시";
			            app.getContainer().redraw();
			        }

			    } catch(error) {
			        console.error("❌ 처리 오류:", error);
			        alert("분석 중 오류가 발생했습니다. 콘솔을 확인하세요.");
			    }
			}
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsOrder");
			dataSet_1.parseData({
				"columns" : [
					{"name": "reqDate"},
					{"name": "clientName"},
					{"name": "itemName"},
					{"name": "orderCount"},
					{"name": "food"}
				]
			});
			app.register(dataSet_1);
			var dataMap_1 = new cpr.data.DataMap("dmSample");
			dataMap_1.parseData({
				"columns" : [
					{
						"name": "reqDate",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "clientName",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "itemName",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "orderCount",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "food",
						"dataType": "string",
						"displayOnly": false
					}
				]
			});
			app.register(dataMap_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "Button";
			if(typeof onBtnSmartMapFillClick == "function") {
				button_1.addEventListener("click", onBtnSmartMapFillClick);
			}
			container.addChild(button_1, {
				"top": "38px",
				"left": "685px",
				"width": "144px",
				"height": "40px"
			});
			
			var textArea_1 = new cpr.controls.TextArea("txaUserInput");
			textArea_1.value = "오늘 날짜로 임채명 데이터추가";
			container.addChild(textArea_1, {
				"top": "10px",
				"left": "10px",
				"width": "553px",
				"height": "137px"
			});
			
			var output_1 = new cpr.controls.Output("optLog");
			output_1.value = "Output";
			output_1.unselectable = false;
			container.addChild(output_1, {
				"top": "523px",
				"left": "13px",
				"width": "873px",
				"height": "1314px"
			});
			
			var group_1 = new cpr.controls.Container();
			group_1.style.setClasses(["cl-form-group"]);
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = true;
			formLayout_1.horizontalSpacing = "10px";
			formLayout_1.verticalSpacing = "10px";
			formLayout_1.topMargin = "5px";
			formLayout_1.rightMargin = "5px";
			formLayout_1.bottomMargin = "5px";
			formLayout_1.leftMargin = "5px";
			formLayout_1.horizontalSeparatorType = "BY_CLASS";
			formLayout_1.verticalSeparatorType = "BY_CLASS";
			formLayout_1.horizontalSeparatorWidth = 1;
			formLayout_1.verticalSeparatorWidth = 1;
			formLayout_1.setColumns(["100px", "1fr"]);
			formLayout_1.setUseColumnShade(0, true);
			formLayout_1.setRows(["25px", "25px", "25px", "25px", "1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_2 = new cpr.controls.Output();
				output_2.value = "reqDate";
				output_2.unselectable = false;
				container.addChild(output_2, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "clientName";
				output_3.unselectable = false;
				container.addChild(output_3, {
					"colIndex": 0,
					"rowIndex": 1
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "itemame";
				output_4.unselectable = false;
				container.addChild(output_4, {
					"colIndex": 0,
					"rowIndex": 2
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "orderCount";
				output_5.unselectable = false;
				container.addChild(output_5, {
					"colIndex": 0,
					"rowIndex": 3
				});
				var output_6 = new cpr.controls.Output();
				output_6.value = "food";
				output_6.unselectable = false;
				container.addChild(output_6, {
					"colIndex": 0,
					"rowIndex": 4
				});
				var output_7 = new cpr.controls.Output();
				output_7.bind("value").toDataMap(app.lookup("dmSample"), "reqDate");
				container.addChild(output_7, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var output_8 = new cpr.controls.Output();
				output_8.bind("value").toDataMap(app.lookup("dmSample"), "clientName");
				container.addChild(output_8, {
					"colIndex": 1,
					"rowIndex": 1
				});
				var output_9 = new cpr.controls.Output();
				output_9.bind("value").toDataMap(app.lookup("dmSample"), "itemName");
				container.addChild(output_9, {
					"colIndex": 1,
					"rowIndex": 2
				});
				var output_10 = new cpr.controls.Output();
				output_10.bind("value").toDataMap(app.lookup("dmSample"), "orderCount");
				container.addChild(output_10, {
					"colIndex": 1,
					"rowIndex": 3
				});
				var output_11 = new cpr.controls.Output();
				output_11.bind("value").toDataMap(app.lookup("dmSample"), "food");
				container.addChild(output_11, {
					"colIndex": 1,
					"rowIndex": 4
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "169px",
				"left": "13px",
				"width": "816px",
				"height": "313px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "QwenDm";
	cpr.core.Platform.INSTANCE.register(app);
})();
