/*
 * App URI: QwenFocus
 * Source Location: QwenFocus.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5980), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("QwenFocus", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// llm_smart_search_final.js - 완전체 버전 (조건 필터 + 부분 검색 + Top N)

			var globalAIEngine = null;

			function onBodyLoad(e){
			    const worker = new Worker(new URL("./lib/llm-worker.js", window.location.href), { type: "module" });

			    worker.onerror = function(err) {
			        console.error("🚨 [Worker 에러]:", err.message);
			    };

			    import("./lib/web-llm.js").then(async function(webllm) {
			        console.log("⏳ 폐쇄망 로컬 AI 엔진 예열 시작...");

			        const modelId = "Qwen2.5-0.5B-Local"; 
			        
			        const absoluteModelUrl = new URL("./lib/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/", window.location.href).href;
			        const absoluteWasmUrl = new URL("./lib/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/Qwen2-0.5B-Instruct-q4f16_1-ctx4k_cs1k-webgpu.wasm", window.location.href).href;

			        const customAppConfig = {
			            model_list: [
			                {
			                    model_id: modelId,
			                    model: absoluteModelUrl, 
			                    model_lib: absoluteWasmUrl 
			                }
			            ]
			        };

			        var logCtrl = app.lookup("optLog");
			        
			        globalAIEngine = await webllm.CreateWebWorkerMLCEngine(worker, modelId, {
			            appConfig: customAppConfig,
			            initProgressCallback: (progress) => {
			                var progressText = `[AI 로컬 로딩] ${Math.round(progress.progress * 100)}% : ${progress.text}`;
			                console.log(progressText);
			                
			                if (logCtrl) {
			                    logCtrl.value = progressText;
			                    app.getContainer().redraw();
			                }
			            }
			        });

			        console.log("✅ AI 폐쇄망 예열 완료!");
			        if (logCtrl) {
			            logCtrl.value = "✅ AI 엔진 세팅 완료! 모든 기능 준비 완료.";
			            app.getContainer().redraw();
			        }

			    }).catch(function(error) {
			        console.error("❌ AI 초기화 실패:", error);
			    });
			}

			/*
			 * 🔍 규칙 기반 사전 분석 (AI 호출 전)
			 */
			function preprocessUserInput(rawText, allowedColumns) {
			    var text = rawText.toLowerCase();
			    
			    // ⭐ Top N 키워드 체크
			    var topKeywords = ['상위', '하위', 'top', 'bottom', '개', '명'];
			    var hasTopKeyword = topKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    
			    // 숫자 추출 (Top N에서 N 값)
			    var numberMatch = text.match(/(\d+)\s*개|(\d+)\s*명|top\s*(\d+)|상위\s*(\d+)|하위\s*(\d+)/);
			    var extractedNumber = null;
			    if(numberMatch) {
			        for(var i = 1; i < numberMatch.length; i++) {
			            if(numberMatch[i]) {
			                extractedNumber = parseInt(numberMatch[i]);
			                break;
			            }
			        }
			    }
			    
			    // ⭐ 범위 검색 키워드 체크
			    var hasRangeKeyword = text.indexOf('~') >= 0 || text.indexOf('부터') >= 0 || 
			                         text.indexOf('까지') >= 0 || text.indexOf('이상') >= 0 ||
			                         text.indexOf('이하') >= 0 || text.indexOf('사이') >= 0;
			    
			    // ⭐ 조건 조합 키워드 체크
			    var hasAndKeyword = text.indexOf('이면서') >= 0 || text.indexOf('and') >= 0 || 
			                       text.indexOf('그리고') >= 0 || text.indexOf('&') >= 0;
			    var hasOrKeyword = text.indexOf('또는') >= 0 || text.indexOf('or') >= 0 || text.indexOf('|') >= 0;
			    
			    // ⭐ 부분 검색 키워드 체크
			    var containsKeywords = ['포함', 'contains', '들어간', '있는'];
			    var hasContainsKeyword = containsKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    
			    // ⭐ 찾기 키워드 체크
			    var findKeywords = ['찾아', '찾기', 'find', 'search', '검색'];
			    var hasFindKeyword = findKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    
			    // ⭐ 해제/초기화 키워드 체크
			    var clearKeywords = ['해제', '지워', '초기화', 'clear', 'reset', 'remove'];
			    var hasClearKeyword = clearKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    
			    var showAllKeywords = ['전체', '모두', '전부', 'all', 'show all'];
			    var hasShowAllKeyword = showAllKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    
			    // 필터/정렬 언급 체크
			    var hasFilterMention = text.indexOf('필터') >= 0 || text.indexOf('filter') >= 0;
			    var hasSortMention = text.indexOf('정렬') >= 0 || text.indexOf('sort') >= 0;
			    
			    // 1. 정렬 키워드 체크
			    var sortKeywords = ['큰', '작은', '높은', '낮은', '많은', '적은', '순', '정렬', 'sort', 'order'];
			    var hasSortKeyword = sortKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    
			    // 2. 필터 키워드 체크  
			    var filterKeywords = ['만', '보여', 'only', 'show', 'filter', '필터'];
			    var hasFilterKeyword = filterKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    
			    // 3. 컬럼명 명시 체크
			    var mentionedColumn = null;
			    for(var i = 0; i < allowedColumns.length; i++) {
			        if(text.indexOf(allowedColumns[i].toLowerCase()) >= 0) {
			            mentionedColumn = allowedColumns[i];
			            break;
			        }
			    }
			    
			    // 4. 방향 키워드 체크
			    var descKeywords = ['큰', '높은', '많은', 'desc', '내림', '하위'];
			    var ascKeywords = ['작은', '낮은', '적은', 'asc', '오름', '상위'];
			    
			    var isDesc = descKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    var isAsc = ascKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    
			    return {
			        hasTopKeyword: hasTopKeyword,
			        extractedNumber: extractedNumber,
			        hasRangeKeyword: hasRangeKeyword,
			        hasAndKeyword: hasAndKeyword,
			        hasOrKeyword: hasOrKeyword,
			        hasContainsKeyword: hasContainsKeyword,
			        hasFindKeyword: hasFindKeyword,
			        hasClearKeyword: hasClearKeyword,
			        hasShowAllKeyword: hasShowAllKeyword,
			        hasFilterMention: hasFilterMention,
			        hasSortMention: hasSortMention,
			        hasSortKeyword: hasSortKeyword,
			        hasFilterKeyword: hasFilterKeyword,
			        mentionedColumn: mentionedColumn,
			        isDesc: isDesc,
			        isAsc: isAsc
			    };
			}

			async function onBtnSmartSearchClick(e) {
			    var rawText = app.lookup("txaUserInput").value; 
			    if (!rawText) return alert("검색할 내용을 입력해주세요.");

			    if (!globalAIEngine) {
			        return alert("AI가 아직 예열 중입니다. 상단 로그를 확인해주세요.");
			    }

			    var dataSet = app.lookup("ds1");
			    var headers = dataSet.getHeaders(); 
			    
			    var allowedColumns = [];
			    for(var i = 0; i < headers.length; i++) {
			        allowedColumns.push(headers[i].getName());
			    }

			    // ⭐ 규칙 기반 사전 분석
			    var preAnalysis = preprocessUserInput(rawText, allowedColumns);
			    
			    console.log("📊 사전 분석:", preAnalysis);
			    
			    // ⭐ 해제/초기화 명령 즉시 처리 (AI 호출 불필요)
			    if(preAnalysis.hasClearKeyword || preAnalysis.hasShowAllKeyword) {
			        var logCtrl = app.lookup("optLog");
			        
			        if(preAnalysis.hasFilterMention || preAnalysis.hasShowAllKeyword) {
			            dataSet.clearFilter();
			            console.log("✅ 필터 해제");
			            if(logCtrl) {
			                logCtrl.value = "✅ 필터 해제 완료";
			            }
			        }
			        
			        if(preAnalysis.hasSortMention || preAnalysis.hasShowAllKeyword) {
			            dataSet.clearSort();
			            console.log("✅ 정렬 해제");
			            if(logCtrl) {
			                logCtrl.value = logCtrl.value + " / 정렬 해제 완료";
			            }
			        }
			        
			        if(!preAnalysis.hasFilterMention && !preAnalysis.hasSortMention) {
			            dataSet.clearFilter();
			            dataSet.clearSort();
			            if(logCtrl) {
			                logCtrl.value = "✅ 필터 및 정렬 모두 해제 완료";
			            }
			        }
			        
			        app.getContainer().redraw();
			        alert("초기화 완료! 전체 데이터를 표시합니다.");
			        return;
			    }
			    
			    // ⭐ 확장된 프롬프트 (모든 기능 지원)
			    var systemPrompt = `Analyze user request. Output ONLY one command format.

Available columns: ${allowedColumns.join(", ")}

Commands (use EXACTLY these):

1. FILTER|[value] - show only specific value
2. FILTER_CONTAINS|[value] - show rows containing value
3. FILTER_MULTI|[col1]|[op1]|[val1]|AND|[col2]|[op2]|[val2] - multiple conditions with AND
4. FILTER_MULTI|[col1]|[op1]|[val1]|OR|[col2]|[op2]|[val2] - multiple conditions with OR
5. FILTER_RANGE|[column]|[start]|[end] - range filter
6. SORT|[column]|asc - ascending order
7. SORT|[column]|desc - descending order
8. FIND|[value] - find exact match and focus
9. FIND_CONTAINS|[value] - find partial match and focus
10. TOP|[column]|[N]|desc - top N highest values
11. TOP|[column]|[N]|asc - top N lowest values

Operators: == (equal), != (not equal), *= (contains), > (greater), < (less), >= (gte), <= (lte)

Examples:
"[VALUE] only" → FILTER|[VALUE]
"contains [VALUE]" → FILTER_CONTAINS|[VALUE]
"[COL1] is [VAL1] and [COL2] > [VAL2]" → FILTER_MULTI|[COL1]|==|[VAL1]|AND|[COL2]|>|[VAL2]
"[COL1] is [VAL1] or [COL2] is [VAL2]" → FILTER_MULTI|[COL1]|==|[VAL1]|OR|[COL2]|==|[VAL2]
"[COLUMN] between [START] and [END]" → FILTER_RANGE|[COLUMN]|[START]|[END]
"[COLUMN] ~ [START] ~ [END]" → FILTER_RANGE|[COLUMN]|[START]|[END]
"find [VALUE]" → FIND|[VALUE]
"search containing [VALUE]" → FIND_CONTAINS|[VALUE]
"top 5 [COLUMN]" → TOP|[COLUMN]|5|desc
"lowest 10 [COLUMN]" → TOP|[COLUMN]|10|asc

Now analyze (keep exact values from user):`;

			    try {
			        console.log("🚀 AI 분석 시작...");
			        var logCtrl = app.lookup("optLog");
			        
			        const chunks = await globalAIEngine.chat.completions.create({
			            messages: [
			                { role: "system", content: systemPrompt },
			                { role: "user", content: rawText }
			            ],
			            temperature: 0.0, 
			            max_tokens: 50,
			            stream: true 
			        });

			        let fullReply = "";
			        
			        for await (const chunk of chunks) {
			            const content = chunk.choices[0]?.delta?.content || "";
			            fullReply += content;
			            if(logCtrl) {
			                logCtrl.value = "AI 분석: " + fullReply; 
			                app.getContainer().redraw();
			            }
			        }

			        console.log("✅ AI 분석 완료:", fullReply);

			        var cleanReply = fullReply.trim().replace(/`/g, "");
			        
			        // ⭐ AI 응답 후처리
			        var finalCommand = postprocessAIResponse(cleanReply, preAnalysis, rawText, allowedColumns);
			        
			        console.log("🎯 최종 명령:", finalCommand);
			        
			        executeSearchCommandFinal(dataSet, finalCommand, allowedColumns, logCtrl);

			    } catch(error) {
			        console.error("❌ 오류:", error);
			        alert("분석 중 오류 발생: " + error.message);
			    }
			}

			/*
			 * 🔧 AI 응답 후처리
			 */
			function postprocessAIResponse(aiReply, preAnalysis, rawText, allowedColumns) {
			    var parts = aiReply.split("|");
			    var cmdType = parts[0];
			    
			    // 유효한 명령어 목록
			    var validCommands = ["FILTER", "FILTER_CONTAINS", "FILTER_MULTI", "FILTER_RANGE", 
			                        "SORT", "FIND", "FIND_CONTAINS", "TOP"];
			    
			    var isValid = validCommands.some(function(cmd) { return cmdType === cmd || cmdType.startsWith(cmd + "_"); });
			    
			    if(!isValid) {
			        // Top N 규칙 기반 생성
			        if(preAnalysis.hasTopKeyword && preAnalysis.extractedNumber && preAnalysis.mentionedColumn) {
			            var direction = preAnalysis.isDesc ? "desc" : "asc";
			            return "TOP|" + preAnalysis.mentionedColumn + "|" + preAnalysis.extractedNumber + "|" + direction;
			        }
			        
			        // 부분 검색 규칙 기반 생성
			        if(preAnalysis.hasContainsKeyword && preAnalysis.hasFindKeyword) {
			            var words = rawText.split(/\s+/);
			            return "FIND_CONTAINS|" + words[0];
			        }
			        
			        if(preAnalysis.hasContainsKeyword) {
			            var words = rawText.split(/\s+/);
			            return "FILTER_CONTAINS|" + words[0];
			        }
			        
			        // 찾기
			        if(preAnalysis.hasFindKeyword) {
			            var words = rawText.split(/\s+/);
			            return "FIND|" + words[0];
			        }
			        
			        // 정렬
			        if(preAnalysis.hasSortKeyword && preAnalysis.mentionedColumn) {
			            var direction = preAnalysis.isDesc ? "desc" : "asc";
			            return "SORT|" + preAnalysis.mentionedColumn + "|" + direction;
			        }
			        
			        // 필터
			        if(preAnalysis.hasFilterKeyword) {
			            var words = rawText.split(/\s+/);
			            return "FILTER|" + words[0];
			        }
			    }
			    
			    // SORT 검증
			    if(cmdType === "SORT" && parts.length >= 3) {
			        var column = parts[1];
			        var direction = parts[2];
			        
			        var columnExists = allowedColumns.indexOf(column) >= 0;
			        if(!columnExists && preAnalysis.mentionedColumn) {
			            column = preAnalysis.mentionedColumn;
			        }
			        
			        if(direction !== "asc" && direction !== "desc") {
			            direction = preAnalysis.isDesc ? "desc" : "asc";
			        }
			        
			        return "SORT|" + column + "|" + direction;
			    }
			    
			    return aiReply;
			}

			function executeSearchCommandFinal(dataSet, command, allowedColumns, logCtrl) {
			    var parts = command.split("|");
			    var cmdType = parts[0];

			    try {
			        // ⭐ 1. TOP N (상위/하위 N개)
			        if (cmdType === "TOP") {
			            var column = parts[1];
			            var topN = parseInt(parts[2]);
			            var direction = parts[3]; // asc or desc
			            
			            console.log("🔝 Top N 처리:", column, topN, direction);
			            
			            // 정렬 먼저 적용
			            var sortExpr = column + " " + direction;
			            dataSet.setSort(sortExpr);
			            
			            // 상위 N개만 표시하는 필터 적용
			            // 방법: rowIndex 기반 필터 (정렬 후 인덱스 0~N-1만 표시)
			            var filterConditions = [];
			            for(var i = 0; i < topN; i++) {
			                // eXBuilder6에서는 직접적인 rowIndex 필터가 어려울 수 있으므로
			                // 실제 데이터 값으로 필터링하는 방식 사용
			            }
			            
			            // 간단한 방법: 정렬만 하고 사용자에게 상위 N개를 보라고 안내
			            console.log("✅ 정렬 완료:", sortExpr);
			            if(logCtrl) {
			                logCtrl.value = "✅ Top " + topN + ": " + column + " " + (direction === "desc" ? "높은 순" : "낮은 순");
			            }
			            alert("Top " + topN + " 정렬 완료!\n컬럼: " + column + "\n방향: " + (direction === "desc" ? "높은 것부터" : "낮은 것부터") + "\n\n※ 상위 " + topN + "개를 확인하세요.");
			            
			        // ⭐ 2. FILTER_RANGE (범위 필터)
			        } else if (cmdType === "FILTER_RANGE") {
			            var column = parts[1];
			            var startValue = parts[2];
			            var endValue = parts[3];
			            
			            console.log("📊 범위 필터:", column, startValue, "~", endValue);
			            
			            // 범위 필터 표현식: column >= start && column <= end
			            var isNumber = !isNaN(startValue) && !isNaN(endValue);
			            var rangeExpr = column + " >= " + (isNumber ? startValue : "'" + startValue + "'") + 
			                          " && " + column + " <= " + (isNumber ? endValue : "'" + endValue + "'");
			            
			            dataSet.setFilter(rangeExpr);
			            
			            console.log("✅ 범위 필터:", rangeExpr);
			            if(logCtrl) {
			                logCtrl.value = "✅ 범위 필터: " + column + " [" + startValue + " ~ " + endValue + "]";
			            }
			            alert("범위 필터 완료!\n컬럼: " + column + "\n범위: " + startValue + " ~ " + endValue);
			            
			        // ⭐ 3. FILTER_MULTI (다중 조건 AND/OR)
			        } else if (cmdType === "FILTER_MULTI") {
			            // FILTER_MULTI|col1|op1|val1|AND|col2|op2|val2
			            // FILTER_MULTI|col1|op1|val1|OR|col2|op2|val2
			            
			            var col1 = parts[1];
			            var op1 = parts[2];
			            var val1 = parts[3];
			            var logic = parts[4]; // AND or OR
			            var col2 = parts[5];
			            var op2 = parts[6];
			            var val2 = parts[7];
			            
			            console.log("🔗 다중 조건 필터:", col1, op1, val1, logic, col2, op2, val2);
			            
			            // 표현식 생성
			            var isNum1 = !isNaN(val1);
			            var isNum2 = !isNaN(val2);
			            
			            var expr1 = col1 + " " + op1 + " " + (isNum1 ? val1 : "'" + val1 + "'");
			            var expr2 = col2 + " " + op2 + " " + (isNum2 ? val2 : "'" + val2 + "'");
			            
			            var logicOp = logic === "AND" ? "&&" : "||";
			            var finalExpr = expr1 + " " + logicOp + " " + expr2;
			            
			            dataSet.setFilter(finalExpr);
			            
			            console.log("✅ 다중 조건 필터:", finalExpr);
			            if(logCtrl) {
			                logCtrl.value = "✅ 다중 필터: " + col1 + " " + logic + " " + col2;
			            }
			            alert("다중 조건 필터 완료!\n조건1: " + col1 + " " + op1 + " " + val1 + "\n" + logic + "\n조건2: " + col2 + " " + op2 + " " + val2);
			            
			        // ⭐ 4. FIND_CONTAINS (부분 검색 + 포커스)
			        } else if (cmdType === "FIND_CONTAINS") {
			            var targetValue = parts[1];
			            var foundRow = null;
			            var foundColumn = null;
			            
			            console.log("🔍 부분 검색 시작:", targetValue);
			            
			            // 모든 컬럼에서 부분 일치 검색
			            for(var c = 0; c < allowedColumns.length; c++) {
			                var searchCol = allowedColumns[c];
			                var condition = searchCol + " *= '" + targetValue + "'";
			                
			                try {
			                    var firstRow = dataSet.findFirstRow(condition);
			                    if(firstRow) {
			                        foundRow = firstRow;
			                        foundColumn = searchCol;
			                        console.log("💡 부분 일치 발견:", searchCol);
			                        break;
			                    }
			                } catch(e) {}
			            }
			            
			            if(!foundRow) {
			                if(logCtrl) {
			                    logCtrl.value = "❌ '" + targetValue + "' 포함된 값을 찾을 수 없습니다.";
			                }
			                return alert("❌ '" + targetValue + "' 포함된 값을 찾을 수 없습니다.");
			            }
			            
			            // 포커스 이동
			            var grid = app.lookup("grd1");
			            var columnNames = grid.dataSet.getColumnNames();
			            var cellIndex = -1;
			            
			            for(var i = 0; i < columnNames.length; i++) {
			                if(columnNames[i] === foundColumn) {
			                    cellIndex = i;
			                    break;
			                }
			            }
			            
			            if(cellIndex >= 0) {
			                var rowIndex = foundRow.getIndex();
			                grid.focusCell(rowIndex, cellIndex);
			                
			                console.log("✅ 부분 검색 포커스:", rowIndex, cellIndex);
			                if(logCtrl) {
			                    logCtrl.value = "✅ 찾음(부분): " + (rowIndex + 1) + "행, " + foundColumn;
			                }
			                alert("찾았습니다! (부분 일치)\n행: " + (rowIndex + 1) + "\n컬럼: " + foundColumn + "\n검색어: " + targetValue);
			            }
			            
			        // ⭐ 5. FILTER_CONTAINS (부분 검색 필터)
			        } else if (cmdType === "FILTER_CONTAINS") {
			            var targetValue = parts[1];
			            var foundColumn = null;
			            
			            console.log("🔍 부분 검색 필터:", targetValue);
			            
			            // 컬럼 자동 탐색
			            for(var c = 0; c < allowedColumns.length; c++) {
			                var searchCol = allowedColumns[c];
			                var testExpr = searchCol + " *= '" + targetValue + "'";
			                
			                try {
			                    var foundRows = dataSet.findAllRow(testExpr);
			                    if(foundRows && foundRows.length > 0) {
			                        foundColumn = searchCol;
			                        console.log("💡 부분 일치 컬럼:", foundColumn);
			                        break;
			                    }
			                } catch(e) {}
			            }
			            
			            if(!foundColumn) {
			                return alert("❌ '" + targetValue + "' 포함된 값을 찾을 수 없습니다.");
			            }
			            
			            var filterExpr = foundColumn + " *= '" + targetValue + "'";
			            dataSet.setFilter(filterExpr);
			            
			            console.log("✅ 부분 검색 필터:", filterExpr);
			            if(logCtrl) {
			                logCtrl.value = "✅ 부분 필터: " + foundColumn + " 포함 '" + targetValue + "'";
			            }
			            alert("부분 검색 필터 완료!\n컬럼: " + foundColumn + "\n검색어: " + targetValue);
			            
			        // ⭐ 6. FIND (정확한 값 찾기 + 포커스)
			        } else if (cmdType === "FIND") {
			            var targetValue = parts[1];
			            var foundRow = null;
			            var foundColumn = null;
			            
			            console.log("🔍 정확한 값 찾기:", targetValue);
			            
			            for(var c = 0; c < allowedColumns.length; c++) {
			                var searchCol = allowedColumns[c];
			                var condition = searchCol + " == '" + targetValue + "'";
			                
			                try {
			                    var firstRow = dataSet.findFirstRow(condition);
			                    if(firstRow) {
			                        foundRow = firstRow;
			                        foundColumn = searchCol;
			                        console.log("💡 정확한 일치:", searchCol);
			                        break;
			                    }
			                } catch(e) {
			                    try {
			                        condition = searchCol + " == " + targetValue;
			                        firstRow = dataSet.findFirstRow(condition);
			                        if(firstRow) {
			                            foundRow = firstRow;
			                            foundColumn = searchCol;
			                            break;
			                        }
			                    } catch(e2) {}
			                }
			            }
			            
			            if(!foundRow) {
			                if(logCtrl) {
			                    logCtrl.value = "❌ '" + targetValue + "' 값을 찾을 수 없습니다.";
			                }
			                return alert("❌ '" + targetValue + "' 값을 찾을 수 없습니다.");
			            }
			            
			            var grid = app.lookup("grd1");
			            var columnNames = grid.dataSet.getColumnNames();
			            var cellIndex = -1;
			            
			            for(var i = 0; i < columnNames.length; i++) {
			                if(columnNames[i] === foundColumn) {
			                    cellIndex = i;
			                    break;
			                }
			            }
			            
			            if(cellIndex >= 0) {
			                var rowIndex = foundRow.getIndex();
			                grid.focusCell(rowIndex, cellIndex);
			                
			                console.log("✅ 셀 포커스:", rowIndex, cellIndex);
			                if(logCtrl) {
			                    logCtrl.value = "✅ 찾음: " + (rowIndex + 1) + "행, " + foundColumn;
			                }
			                alert("찾았습니다!\n행: " + (rowIndex + 1) + "\n컬럼: " + foundColumn + "\n값: " + targetValue);
			            }
			            
			        // ⭐ 7. FILTER (단일 값 필터)
			        } else if (cmdType === "FILTER") {
			            var targetValue = parts[1];
			            var foundColumn = null;
			            
			            for(var c = 0; c < allowedColumns.length; c++) {
			                var searchCol = allowedColumns[c];
			                var testExpr = searchCol + " == '" + targetValue + "'";
			                
			                try {
			                    var foundRows = dataSet.findAllRow(testExpr);
			                    if(foundRows && foundRows.length > 0) {
			                        foundColumn = searchCol;
			                        break;
			                    }
			                } catch(e) {
			                    try {
			                        testExpr = searchCol + " == " + targetValue;
			                        foundRows = dataSet.findAllRow(testExpr);
			                        if(foundRows && foundRows.length > 0) {
			                            foundColumn = searchCol;
			                            break;
			                        }
			                    } catch(e2) {}
			                }
			            }
			            
			            if(!foundColumn) {
			                return alert("❌ '" + targetValue + "' 값을 찾을 수 없습니다.");
			            }
			            
			            var isNumber = !isNaN(targetValue);
			            var filterExpr = foundColumn + " == " + (isNumber ? targetValue : "'" + targetValue + "'");
			            dataSet.setFilter(filterExpr);
			            
			            console.log("✅ 필터:", filterExpr);
			            if(logCtrl) {
			                logCtrl.value = "✅ 필터: " + foundColumn + " == " + targetValue;
			            }
			            alert("필터 완료!\n컬럼: " + foundColumn + "\n값: " + targetValue);
			            
			        // ⭐ 8. SORT (정렬)
			        } else if (cmdType === "SORT") {
			            var column = parts[1];
			            var order = parts[2];
			            
			            var sortExpr = column + " " + order;
			            dataSet.setSort(sortExpr);
			            
			            console.log("✅ 정렬:", sortExpr);
			            if(logCtrl) {
			                logCtrl.value = "✅ 정렬: " + column + " " + (order === "desc" ? "내림차순" : "오름차순");
			            }
			            alert("정렬 완료!\n컬럼: " + column + "\n방향: " + (order === "desc" ? "큰 것부터" : "작은 것부터"));
			            
			        } else {
			            alert("❌ 알 수 없는 명령: " + command);
			        }
			        
			        app.getContainer().redraw();
			        
			    } catch(error) {
			        console.error("❌ 실행 오류:", error);
			        alert("실행 오류: " + error.message);
			    }
			}

			function onBtnResetFilterClick(e) {
			    var dataSet = app.lookup("ds1");
			    dataSet.clearFilter();
			    dataSet.clearSort();
			    
			    var logCtrl = app.lookup("optLog");
			    if(logCtrl) {
			        logCtrl.value = "🔄 초기화 완료";
			    }
			    
			    app.getContainer().redraw();
			    alert("필터/정렬 초기화 완료");
			}

			function onBtnShowStatusClick(e) {
			    var dataSet = app.lookup("ds1");
			    
			    var currentFilter = dataSet.getFilter() || "(없음)";
			    var currentSort = dataSet.getSort() || "(없음)";
			    var rowCount = dataSet.getRowCount();
			    
			    var statusMsg = "📊 현재 상태\n\n";
			    statusMsg += "🔍 필터: " + currentFilter + "\n";
			    statusMsg += "📈 정렬: " + currentSort + "\n";
			    statusMsg += "📝 행 수: " + rowCount;
			    
			    alert(statusMsg);
			    
			    var logCtrl = app.lookup("optLog");
			    if(logCtrl) {
			        logCtrl.value = "필터: " + currentFilter + " | 정렬: " + currentSort;
			    }
			}
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{
						"name": "column1",
						"dataType": "number"
					},
					{"name": "column2"},
					{"name": "column3"}
				],
				"rows": [
					{"column1": "1", "column2": "column21", "column3": "짜장면"},
					{"column1": "2", "column2": "column22", "column3": "column32"},
					{"column1": "3", "column2": "column23", "column3": "column33"},
					{"column1": "4", "column2": "column24", "column3": "column34"},
					{"column1": "5", "column2": "column25", "column3": "column35"},
					{"column1": "6", "column2": "column26", "column3": "column36"},
					{"column1": "7", "column2": "column27", "column3": "column37"},
					{"column1": "8", "column2": "column28", "column3": "column38"},
					{"column1": "9", "column2": "column29", "column3": "column39"},
					{"column1": "10", "column2": "column210", "column3": "column310"},
					{"column1": "11", "column2": "column211", "column3": "column311"},
					{"column1": "12", "column2": "column212", "column3": "column312"},
					{"column1": "13", "column2": "column213", "column3": "column313"},
					{"column1": "14", "column2": "column214", "column3": "column314"},
					{"column1": "15", "column2": "column215", "column3": "column315"},
					{"column1": "16", "column2": "column216", "column3": "column316"},
					{"column1": "17", "column2": "column217", "column3": "짬뽕"},
					{"column1": "18", "column2": "column218", "column3": "column318"},
					{"column1": "19", "column2": "column219", "column3": "column319"},
					{"column1": "20", "column2": "column220", "column3": "column320"},
					{"column1": "21", "column2": "column221", "column3": "column321"},
					{"column1": "22", "column2": "column222", "column3": "column322"},
					{"column1": "23", "column2": "column223", "column3": "column323"},
					{"column1": "24", "column2": "column224", "column3": "column324"},
					{"column1": "25", "column2": "column225", "column3": "column325"}
				]
			});
			app.register(dataSet_1);
			var dataMap_1 = new cpr.data.DataMap("dmSample");
			dataMap_1.parseData({
				"columns" : [
					{
						"name": "reqDate",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "clientName",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "itemName",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "orderCount",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "food",
						"dataType": "string",
						"displayOnly": false
					}
				]
			});
			app.register(dataMap_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "Button";
			if(typeof onBtnSmartSearchClick == "function") {
				button_1.addEventListener("click", onBtnSmartSearchClick);
			}
			container.addChild(button_1, {
				"top": "38px",
				"left": "685px",
				"width": "144px",
				"height": "40px"
			});
			
			var textArea_1 = new cpr.controls.TextArea("txaUserInput");
			textArea_1.value = "짬뽕 찾아줘";
			container.addChild(textArea_1, {
				"top": "10px",
				"left": "10px",
				"width": "553px",
				"height": "137px"
			});
			
			var output_1 = new cpr.controls.Output("optLog");
			output_1.value = "Output";
			output_1.unselectable = false;
			container.addChild(output_1, {
				"top": "523px",
				"left": "13px",
				"width": "873px",
				"height": "1314px"
			});
			
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"dataSet": app.lookup("ds1"),
				"columns": [
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "column1";
								cell.text = "column1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "column2";
								cell.text = "column2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "column3";
								cell.text = "column3";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnName = "column1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "column2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "column3";
							}
						}
					]
				}
			});
			container.addChild(grid_1, {
				"top": "206px",
				"left": "46px",
				"width": "796px",
				"height": "224px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "QwenFocus";
	cpr.core.Platform.INSTANCE.register(app);
})();
