/*
 * App URI: QwenFilter
 * Source Location: QwenFilter.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5980), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("QwenFilter", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// llm_smart_search_v3.js - 범용성 + 하이브리드 방식

			var globalAIEngine = null;

			function onBodyLoad(e){
			    const worker = new Worker(new URL("./lib/llm-worker.js", window.location.href), { type: "module" });

			    worker.onerror = function(err) {
			        console.error("🚨 [Worker 에러]:", err.message);
			    };

			    import("./lib/web-llm.js").then(async function(webllm) {
			        console.log("⏳ 폐쇄망 로컬 AI 엔진 예열 시작...");

			        const modelId = "Qwen2.5-0.5B-Local"; 
			        
			        const absoluteModelUrl = new URL("./lib/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/", window.location.href).href;
			        const absoluteWasmUrl = new URL("./lib/Qwen2.5-0.5B-Instruct-q4f16_1-MLC/Qwen2-0.5B-Instruct-q4f16_1-ctx4k_cs1k-webgpu.wasm", window.location.href).href;

			        const customAppConfig = {
			            model_list: [
			                {
			                    model_id: modelId,
			                    model: absoluteModelUrl, 
			                    model_lib: absoluteWasmUrl 
			                }
			            ]
			        };

			        var logCtrl = app.lookup("optLog");
			        
			        globalAIEngine = await webllm.CreateWebWorkerMLCEngine(worker, modelId, {
			            appConfig: customAppConfig,
			            initProgressCallback: (progress) => {
			                var progressText = `[AI 로컬 로딩] ${Math.round(progress.progress * 100)}% : ${progress.text}`;
			                console.log(progressText);
			                
			                if (logCtrl) {
			                    logCtrl.value = progressText;
			                    app.getContainer().redraw();
			                }
			            }
			        });

			        console.log("✅ AI 폐쇄망 예열 완료!");
			        if (logCtrl) {
			            logCtrl.value = "✅ AI 엔진 세팅 완료! 자연어 검색 준비 끝.";
			            app.getContainer().redraw();
			        }

			    }).catch(function(error) {
			        console.error("❌ AI 초기화 실패:", error);
			    });
			}

			/*
			 * 🔍 규칙 기반 사전 필터링 (AI 호출 전)
			 */
			function preprocessUserInput(rawText, allowedColumns) {
			    var text = rawText.toLowerCase();
			    
			    // 1. 정렬 키워드 체크
			    var sortKeywords = ['큰', '작은', '높은', '낮은', '많은', '적은', '순', '정렬', 'sort', 'order'];
			    var hasSortKeyword = sortKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    
			    // 2. 필터 키워드 체크  
			    var filterKeywords = ['만', '보여', 'only', 'show', 'filter', '필터'];
			    var hasFilterKeyword = filterKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    
			    // 3. 컬럼명 명시 체크
			    var mentionedColumn = null;
			    for(var i = 0; i < allowedColumns.length; i++) {
			        if(text.indexOf(allowedColumns[i].toLowerCase()) >= 0) {
			            mentionedColumn = allowedColumns[i];
			            break;
			        }
			    }
			    
			    // 4. 방향 키워드 체크
			    var descKeywords = ['큰', '높은', '많은', 'desc', '내림'];
			    var ascKeywords = ['작은', '낮은', '적은', 'asc', '오름'];
			    
			    var isDesc = descKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    var isAsc = ascKeywords.some(function(kw) { return text.indexOf(kw) >= 0; });
			    
			    return {
			        hasSortKeyword: hasSortKeyword,
			        hasFilterKeyword: hasFilterKeyword,
			        mentionedColumn: mentionedColumn,
			        isDesc: isDesc,
			        isAsc: isAsc
			    };
			}

			async function onBtnSmartSearchClick(e) {
			    var rawText = app.lookup("txaUserInput").value; 
			    if (!rawText) return alert("검색할 내용을 입력해주세요.");

			    if (!globalAIEngine) {
			        return alert("AI가 아직 예열 중입니다. 상단 로그를 확인해주세요.");
			    }

			    var dataSet = app.lookup("ds1");
			    var headers = dataSet.getHeaders(); 
			    
			    var allowedColumns = [];
			    for(var i = 0; i < headers.length; i++) {
			        allowedColumns.push(headers[i].getName());
			    }

			    // ⭐ 규칙 기반 사전 분석
			    var preAnalysis = preprocessUserInput(rawText, allowedColumns);
			    
			    console.log("📊 사전 분석:", preAnalysis);
			    
			    // ⭐ 범용적 프롬프트 (특정 값 예시 제거)
			    var systemPrompt = `Analyze user request. Output ONLY one command format.

Available columns: ${allowedColumns.join(", ")}

Commands (use EXACTLY these):
1. FILTER|[value] - when user wants to see only specific value
2. SORT|[column]|asc - when user wants ascending order
3. SORT|[column]|desc - when user wants descending order
4. MULTI|FILTER|[value]|SORT|[column]|[direction] - both filter and sort

Examples (generic):
"[VALUE] only" → FILTER|[VALUE]
"show only [VALUE]" → FILTER|[VALUE]
"[COLUMN] high to low" → SORT|[COLUMN]|desc
"[COLUMN] low to high" → SORT|[COLUMN]|asc
"[COLUMN] biggest first" → SORT|[COLUMN]|desc
"[VALUE] only, sorted by [COLUMN]" → MULTI|FILTER|[VALUE]|SORT|[COLUMN]|asc

Now analyze (keep exact values from user):`;

			    try {
			        console.log("🚀 AI 분석 시작...");
			        var logCtrl = app.lookup("optLog");
			        
			        const chunks = await globalAIEngine.chat.completions.create({
			            messages: [
			                { role: "system", content: systemPrompt },
			                { role: "user", content: rawText }
			            ],
			            temperature: 0.0, 
			            max_tokens: 30,
			            stream: true 
			        });

			        let fullReply = "";
			        
			        for await (const chunk of chunks) {
			            const content = chunk.choices[0]?.delta?.content || "";
			            fullReply += content;
			            if(logCtrl) {
			                logCtrl.value = "AI 분석: " + fullReply; 
			                app.getContainer().redraw();
			            }
			        }

			        console.log("✅ AI 분석 완료:", fullReply);

			        var cleanReply = fullReply.trim().replace(/`/g, "");
			        
			        // ⭐ AI 응답 후처리 (규칙 기반 검증/수정)
			        var finalCommand = postprocessAIResponse(cleanReply, preAnalysis, rawText, allowedColumns);
			        
			        console.log("🎯 최종 명령:", finalCommand);
			        
			        executeSearchCommandV3(dataSet, finalCommand, allowedColumns, logCtrl);

			    } catch(error) {
			        console.error("❌ 오류:", error);
			        alert("분석 중 오류 발생: " + error.message);
			    }
			}

			/*
			 * 🔧 AI 응답 후처리 (검증 및 수정)
			 */
			function postprocessAIResponse(aiReply, preAnalysis, rawText, allowedColumns) {
			    var parts = aiReply.split("|");
			    var cmdType = parts[0];
			    
			    // 1. 잘못된 명령어 수정
			    if(cmdType !== "FILTER" && cmdType !== "SORT" && cmdType !== "MULTI" && 
			       !cmdType.startsWith("FILTER_")) {
			        
			        // 정렬 키워드가 있으면 SORT로 강제 변환
			        if(preAnalysis.hasSortKeyword && preAnalysis.mentionedColumn) {
			            var direction = preAnalysis.isDesc ? "desc" : "asc";
			            return "SORT|" + preAnalysis.mentionedColumn + "|" + direction;
			        }
			        
			        // 필터 키워드가 있으면 FILTER로 강제 변환
			        if(preAnalysis.hasFilterKeyword) {
			            // 사용자 입력에서 값 추출 (간단한 패턴)
			            var words = rawText.split(/\s+/);
			            var valueCandidate = words[0]; // 첫 단어를 임시 값으로
			            return "FILTER|" + valueCandidate;
			        }
			    }
			    
			    // 2. SORT 명령어 검증
			    if(cmdType === "SORT") {
			        if(parts.length >= 3) {
			            var column = parts[1];
			            var direction = parts[2];
			            
			            // 컬럼명 검증
			            var columnExists = allowedColumns.indexOf(column) >= 0;
			            if(!columnExists && preAnalysis.mentionedColumn) {
			                column = preAnalysis.mentionedColumn;
			            }
			            
			            // 방향 검증
			            if(direction !== "asc" && direction !== "desc") {
			                direction = preAnalysis.isDesc ? "desc" : "asc";
			            }
			            
			            return "SORT|" + column + "|" + direction;
			        }
			    }
			    
			    // 3. 원본 그대로 반환
			    return aiReply;
			}

			function executeSearchCommandV3(dataSet, command, allowedColumns, logCtrl) {
			    var parts = command.split("|");
			    var cmdType = parts[0];

			    try {
			        if (cmdType === "FILTER" || cmdType.startsWith("FILTER_")) {
			            
			            var targetValue = parts[1];
			            
			            var operator = "==";
			            if (cmdType === "FILTER_GTE") operator = ">=";
			            else if (cmdType === "FILTER_LTE") operator = "<=";
			            else if (cmdType === "FILTER_GT") operator = ">";
			            else if (cmdType === "FILTER_LT") operator = "<";
			            else if (cmdType === "FILTER_CONTAINS") operator = "*=";
			            
			            var foundColumn = null;
			            
			            for(var c = 0; c < allowedColumns.length; c++) {
			                var searchCol = allowedColumns[c];
			                var testExpr = searchCol + " " + operator + " '" + targetValue + "'";
			                
			                try {
			                    var foundRows = dataSet.findAllRow(testExpr);
			                    
			                    if(foundRows && foundRows.length > 0) {
			                        foundColumn = searchCol;
			                        console.log("💡 컬럼 발견:", foundColumn);
			                        break;
			                    }
			                } catch(e) {
			                    try {
			                        testExpr = searchCol + " " + operator + " " + targetValue;
			                        foundRows = dataSet.findAllRow(testExpr);
			                        
			                        if(foundRows && foundRows.length > 0) {
			                            foundColumn = searchCol;
			                            console.log("💡 컬럼 발견 (숫자):", foundColumn);
			                            break;
			                        }
			                    } catch(e2) {}
			                }
			            }
			            
			            if(!foundColumn) {
			                return alert("❌ '" + targetValue + "' 값을 찾을 수 없습니다.");
			            }
			            
			            var isNumber = !isNaN(targetValue);
			            var filterExpr = foundColumn + " " + operator + " " + (isNumber ? targetValue : "'" + targetValue + "'");
			            dataSet.setFilter(filterExpr);
			            
			            console.log("✅ 필터:", filterExpr);
			            if(logCtrl) {
			                logCtrl.value = "✅ 필터: " + foundColumn + " " + operator + " " + targetValue;
			            }
			            alert("필터 완료!\n컬럼: " + foundColumn + "\n조건: " + operator + " " + targetValue);
			            
			        } else if (cmdType === "SORT") {
			            var column = parts[1];
			            var order = parts[2];
			            
			            var sortExpr = column + " " + order;
			            dataSet.setSort(sortExpr);
			            
			            console.log("✅ 정렬:", sortExpr);
			            if(logCtrl) {
			                logCtrl.value = "✅ 정렬: " + column + " " + (order === "desc" ? "내림차순" : "오름차순");
			            }
			            alert("정렬 완료: " + column + " " + (order === "desc" ? "큰 것부터" : "작은 것부터"));
			            
			        } else if (cmdType === "MULTI") {
			            var filterValue = null;
			            var sortColumn = null;
			            var sortOrder = null;
			            
			            for(var i = 1; i < parts.length; i++) {
			                if(parts[i] === "FILTER" && i + 1 < parts.length) {
			                    filterValue = parts[i + 1];
			                }
			                if(parts[i] === "SORT" && i + 2 < parts.length) {
			                    sortColumn = parts[i + 1];
			                    sortOrder = parts[i + 2];
			                }
			            }
			            
			            if(filterValue) {
			                var foundColumn = null;
			                
			                for(var c = 0; c < allowedColumns.length; c++) {
			                    var searchCol = allowedColumns[c];
			                    var testExpr = searchCol + " == '" + filterValue + "'";
			                    
			                    try {
			                        var foundRows = dataSet.findAllRow(testExpr);
			                        if(foundRows && foundRows.length > 0) {
			                            foundColumn = searchCol;
			                            break;
			                        }
			                    } catch(e) {}
			                }
			                
			                if(foundColumn) {
			                    var filterExpr = foundColumn + " == '" + filterValue + "'";
			                    dataSet.setFilter(filterExpr);
			                    console.log("✅ 필터:", filterExpr);
			                }
			            }
			            
			            if(sortColumn && sortOrder) {
			                var sortExpr = sortColumn + " " + sortOrder;
			                dataSet.setSort(sortExpr);
			                console.log("✅ 정렬:", sortExpr);
			            }
			            
			            if(logCtrl) {
			                logCtrl.value = "✅ 필터 + 정렬 완료!";
			            }
			            alert("필터 및 정렬 완료!");
			            
			        } else {
			            alert("❌ 알 수 없는 명령: " + command);
			        }
			        
			        app.getContainer().redraw();
			        
			    } catch(error) {
			        console.error("❌ 실행 오류:", error);
			        alert("실행 오류: " + error.message);
			    }
			}

			function onBtnResetFilterClick(e) {
			    var dataSet = app.lookup("ds1");
			    dataSet.setFilter("");
			    dataSet.setSort("");
			    
			    var logCtrl = app.lookup("optLog");
			    if(logCtrl) {
			        logCtrl.value = "🔄 초기화 완료";
			    }
			    
			    app.getContainer().redraw();
			    alert("필터/정렬 초기화 완료");
			}

			function onBtnShowStatusClick(e) {
			    var dataSet = app.lookup("ds1");
			    
			    var currentFilter = dataSet.getFilter() || "(없음)";
			    var currentSort = dataSet.getSort() || "(없음)";
			    var rowCount = dataSet.getRowCount();
			    
			    var statusMsg = "📊 현재 상태\n\n";
			    statusMsg += "🔍 필터: " + currentFilter + "\n";
			    statusMsg += "📈 정렬: " + currentSort + "\n";
			    statusMsg += "📝 행 수: " + rowCount;
			    
			    alert(statusMsg);
			    
			    var logCtrl = app.lookup("optLog");
			    if(logCtrl) {
			        logCtrl.value = "필터: " + currentFilter + " | 정렬: " + currentSort;
			    }
			}
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsOrder");
			dataSet_1.parseData({
				"columns" : [
					{"name": "reqDate"},
					{"name": "clientName"},
					{"name": "itemName"},
					{"name": "orderCount"},
					{"name": "food"}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("ds1");
			dataSet_2.parseData({
				"columns": [
					{
						"name": "column1",
						"dataType": "number"
					},
					{"name": "column2"},
					{"name": "column3"}
				],
				"rows": [
					{"column1": "1", "column2": "column21", "column3": "짜장면"},
					{"column1": "2", "column2": "column22", "column3": "column32"},
					{"column1": "3", "column2": "column23", "column3": "column33"},
					{"column1": "4", "column2": "column24", "column3": "column34"},
					{"column1": "5", "column2": "column25", "column3": "column35"},
					{"column1": "6", "column2": "column26", "column3": "column36"},
					{"column1": "7", "column2": "column27", "column3": "column37"}
				]
			});
			app.register(dataSet_2);
			var dataMap_1 = new cpr.data.DataMap("dmSample");
			dataMap_1.parseData({
				"columns" : [
					{
						"name": "reqDate",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "clientName",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "itemName",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "orderCount",
						"dataType": "string",
						"displayOnly": false
					},
					{
						"name": "food",
						"dataType": "string",
						"displayOnly": false
					}
				]
			});
			app.register(dataMap_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "Button";
			if(typeof onBtnSmartSearchClick == "function") {
				button_1.addEventListener("click", onBtnSmartSearchClick);
			}
			container.addChild(button_1, {
				"top": "38px",
				"left": "685px",
				"width": "144px",
				"height": "40px"
			});
			
			var textArea_1 = new cpr.controls.TextArea("txaUserInput");
			textArea_1.value = "오늘 날짜로 임채명 데이터추가";
			container.addChild(textArea_1, {
				"top": "10px",
				"left": "10px",
				"width": "553px",
				"height": "137px"
			});
			
			var output_1 = new cpr.controls.Output("optLog");
			output_1.value = "Output";
			output_1.unselectable = false;
			container.addChild(output_1, {
				"top": "523px",
				"left": "13px",
				"width": "873px",
				"height": "1314px"
			});
			
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"dataSet": app.lookup("ds1"),
				"columns": [
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "column1";
								cell.text = "column1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "column2";
								cell.text = "column2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
								cell.targetColumnName = "column3";
								cell.text = "column3";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnName = "column1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "column2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "column3";
							}
						}
					]
				}
			});
			container.addChild(grid_1, {
				"top": "206px",
				"left": "46px",
				"width": "796px",
				"height": "224px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "QwenFilter";
	cpr.core.Platform.INSTANCE.register(app);
})();
